import pandas as pd
from abc import ABC, abstractmethod
from typing import Callable

import subprocess
import shlex
import os

class Executor(ABC):
    """
    THE BLUEPRINT:
    This is an Abstract Base Class (ABC). It does not actually run any simulations itself.
    Instead, it acts as a strict rulebook for any future executors we build.

    The rule is: Any class that inherits from 'Executor' MUST have a method called 'run',
    it MUST accept a Pandas DataFrame as input, and it MUST return a Pandas DataFrame.
    This guarantees that DigiQual's main loop can talk to ANY solver blindly,
    knowing that '.run()' will always work.
    """

    @abstractmethod
    def run(self, samples: pd.DataFrame) -> pd.DataFrame:
        """
        Executes the simulation for a batch of input samples.

        Args:
            samples (pd.DataFrame): A table of input variables generated by DigiQual
                                    (e.g., columns for 'Length' and 'Angle').

        Returns:
            pd.DataFrame: A table containing both the original inputs and the newly
                            calculated simulation outcomes.
        """
        pass


class PythonExecutor(Executor):
    """
    THE IN-MEMORY TRANSLATOR:
    This executor is for lightweight analytical models or surrogate models written in Python.
    Because it runs entirely inside DigiQual's current memory space, it is incredibly fast.
    However, it should NOT be used for heavy FEA/CFD libraries, as those can cause memory leaks
    if run thousands of times in a single loop.

    Example Usage:
        def my_math_model(row):
            return row['Length'] * 2 + row['Angle']

        executor = PythonExecutor(solver_func=my_math_model, outcome_col='Signal')
    """

    def __init__(self, solver_func: Callable, outcome_col: str):
        """
        Sets up the translator with the user's specific rules.

        Args:
            solver_func (Callable): A user-defined Python function. This function must be designed
                                    to accept a single row of data (a Pandas Series) and return a number.
            outcome_col (str): What we should name the final result column (e.g., 'Max_Stress').
        """
        self.solver_func = solver_func
        self.outcome_col = outcome_col

    def run(self, samples: pd.DataFrame) -> pd.DataFrame:
        """
        The actual translation process for pure Python models.
        """
        print(f"   -> Executing Python model for {len(samples)} points...")

        # Step 1: Make a safe copy of the incoming data so we don't accidentally corrupt it.
        results = samples.copy()

        try:
            # Step 2: The magic line.
            # '.apply' with 'axis=1' tells Pandas to take our DataFrame, slice it into individual rows,
            # and feed each row one-by-one into the user's 'solver_func'.
            # It then takes all the answers and creates a brand new column named by 'outcome_col'.
            results[self.outcome_col] = results.apply(self.solver_func, axis=1)

        except KeyError as e:
            # --- NEW SAFEGUARD: Catch typos inside the user's custom function ---
            print(f"   -> Python simulation FAILED due to a missing variable: {e}")
            print("   -> Tip: Check your solver_func to ensure the column names match exactly!")
            return pd.DataFrame()

        except Exception as e:
            # Step 3: Catch all other mathematical errors gracefully
            print(f"   -> Python simulation FAILED: {e}")
            return pd.DataFrame()

        # Step 4: Return the finished table (Inputs + New Outcome Column) back to DigiQual
        return results




class CLIExecutor(Executor):
    """
    THE HEAVY-DUTY TRANSLATOR (Process Isolation):
    This executor acts like a human sitting at a computer terminal. It takes the DigiQual DataFrame,
    saves it as a CSV file, opens a brand new, isolated terminal command to run your heavy software
    (like Ansys or a heavy Python FEA script), waits for it to finish, and reads the resulting CSV.

    Because the OS opens and closes a separate process for the solver, 100% of the memory used
    by the solver is cleared when it finishes. This prevents memory leaks.

    Example Usage:
        cmd = "python run_abaqus.py {input} {output}"
        executor = CLIExecutor(command_template=cmd)
    """

    def __init__(self, command_template: str, input_path: str = "temp_in.csv", output_path: str = "temp_out.csv"):
        """
        Sets up the terminal command and the temporary file names we will use to pass data.

        Args:
            command_template (str): The exact command you would type into a terminal, but with
                                    {input} and {output} where the file paths should go.
            input_path (str): The name of the file we will create to send data TO the solver.
            output_path (str): The name of the file we expect the solver to create to send data BACK.
        """
        self.command_template = command_template
        self.input_path = input_path
        self.output_path = output_path

    def run(self, samples: pd.DataFrame) -> pd.DataFrame:
        """
        The translation process for heavy, external software.
        """
        # Step 1: Write inputs to CSV
        samples.to_csv(self.input_path, index=False)

        # Step 2 & 3: Format and split the command
        cmd = self.command_template.format(input=self.input_path, output=self.output_path)
        print(f"   -> Executing Isolated Process: {cmd}")
        cmd_list = shlex.split(cmd)

        try:
            # Step 4: Spawn the isolated process
            subprocess.run(cmd_list, shell=False, check=True)
        except subprocess.CalledProcessError as e:
            print(f"   -> Simulation FAILED (Exit Code {e.returncode}).")
            return pd.DataFrame()

        # Step 5: Check if output file exists
        if not os.path.exists(self.output_path):
            print("   -> Simulation failed to produce an output file.")
            return pd.DataFrame()

        # Step 6: Read CSV and Apply Auto-Stitching
        try:
            results = pd.read_csv(self.output_path)

            # --- NEW PROTECTION: Enforce Executor Contract ---
            missing_cols = [c for c in samples.columns if c not in results.columns]

            if missing_cols:
                # If row counts match, safely stitch the inputs back on!
                if len(results) == len(samples):
                    print(f"   -> Info: Auto-stitching missing input columns {missing_cols} back to results.")
                    for col in missing_cols:
                        results[col] = samples[col].values
                else:
                    # If row counts don't match, we cannot safely align the data
                    print(f"   -> ERROR: External solver returned {len(results)} rows, but we sent {len(samples)}.")
                    print(f"   -> Cannot safely align missing input columns {missing_cols}.")
                    return pd.DataFrame() # Fail gracefully

            return results

        except Exception as e:
            print(f"   -> Failed to read output file: {e}")
            return pd.DataFrame()

class MatlabExecutor(CLIExecutor):
    """
    THE MATLAB TRANSLATOR:
    A specialized version of the CLIExecutor designed specifically for MATLAB.
    It automatically handles the complex terminal syntax required to run MATLAB
    in a headless "batch" mode (without opening the graphical interface).

    The user must provide a MATLAB wrapper function that accepts two string arguments:
    the input CSV path and the output CSV path.

    Example Usage:
        # If the user has a file named 'matlab_wrapper.m'
        executor = MatlabExecutor(wrapper_name='matlab_wrapper')
    """

    def __init__(self, wrapper_name: str, input_path: str = "temp_in.csv", output_path: str = "temp_out.csv"):
        """
        Initializes the MATLAB Executor by formatting the correct terminal command.

        Args:
            wrapper_name (str): The name of the top-level MATLAB function (e.g., 'matlab_wrapper').
                                Do not include the '.m' extension.
            input_path (str): Temporary file path to write inputs.
            output_path (str): Temporary file path to read outputs.
        """
        # Safely remove the '.m' extension if the user accidentally included it
        func_name = wrapper_name.replace('.m', '')

        # Construct the MATLAB headless command string.
        # This formats it as: matlab -batch "func_name('{input}', '{output}')" -nosplash -nodesktop
        # We use {{input}} and {{output}} so Python formats the curly braces literally,
        # allowing the parent CLIExecutor to fill them in later with the actual file paths.
        matlab_cmd = f'matlab -batch "{func_name}(\'{{input}}\', \'{{output}}\')" -nosplash -nodesktop'

        # Pass this constructed command to the parent CLIExecutor class.
        # From here, the CLIExecutor's existing 'run' method will handle the rest!
        super().__init__(command_template=matlab_cmd, input_path=input_path, output_path=output_path)
