"""The DigiQual Shiny app: page layout and per-session server wiring.

Each tab lives in its own module (``tab_*.py``) exposing its ``panel`` UI and a
``register(input, output, session, state)`` function with its server code. Shared
reactive values live in `state.AppState`.
"""

import matplotlib

matplotlib.use('Agg')

import warnings  # noqa: E402
from pathlib import Path  # noqa: E402

from faicons import icon_svg  # noqa: E402
from shiny import App, reactive, ui  # noqa: E402

from . import tab_design, tab_diagnostics, tab_explorer, tab_model_fit, tab_uq  # noqa: E402
from .state import AppState, logger, register_shared  # noqa: E402, F401
from .ui_home import home_panel  # noqa: E402

www_dir = Path(__file__).parent / "www"

# MathJax 3 single-file SVG build (no separate font files), vendored in www/ so
# equations render offline. Falls back to the CDN if the file is missing.
_MATHJAX_LOCAL = "mathjax-tex-svg.js"
MATHJAX_SRC = (
    _MATHJAX_LOCAL if (www_dir / _MATHJAX_LOCAL).exists()
    else "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg.js"
)

warnings.filterwarnings(
    "ignore",
    message=".*resource_tracker.*",
    category=UserWarning
)

app_css = (www_dir / "app.css").read_text(encoding="utf-8")


#### UI Definition ####
app_ui = ui.page_navbar(
    home_panel,
    tab_design.panel,
    tab_diagnostics.panel,
    tab_model_fit.panel,
    tab_explorer.panel,
    tab_uq.panel,
    ui.nav_spacer(),
    ui.nav_control(
        ui.input_action_button(
            "btn_restart", "Reset App",
            class_="btn-danger btn-sm",
            style="color: white !important;",
            icon=icon_svg("trash")
        )
    ),
    title="DigiQual",
    id="navbar",
    fillable=True,
    header=ui.tags.head(
        # Generated by scripts/make_icon.py, alongside the desktop app icons
        ui.tags.link(rel="icon", type="image/png", href="favicon.png"),
        ui.tags.style(app_css),
        # MathJax renders the model equation. A vendored copy in www/ keeps the app
        # fully offline (as the desktop app promises); the CDN is only a fallback.
        ui.tags.script(src=MATHJAX_SRC),
        ui.tags.script("""
            Shiny.addCustomMessageHandler('refresh_page', function(message) {
                window.location.reload();
            });
        """)
    )
)


#### Server Definition ####
def server(input, output, session):
    state = AppState(input)

    # Registration order matches the original single-closure server, so effects
    # that fire on the same event still run in the same order.
    tab_design.register(input, output, session, state)
    tab_diagnostics.register(input, output, session, state)
    _register_reset_app(input, session)
    register_shared(input, output, session, state)
    tab_model_fit.register(input, output, session, state)
    tab_explorer.register(input, output, session, state)
    tab_uq.register(input, output, session, state)


def _register_reset_app(input, session):
    """The navbar's Reset App button: confirm, then reload the page."""

    @reactive.effect
    @reactive.event(input.btn_restart)
    def handle_restart():
        """Shows a confirmation modal when the user clicks the Reset button."""
        ui.modal_show(
            ui.modal(
                "Are you sure you want to completely reset the application? This will clear all uploaded data, models, and current progress.",
                title="Confirm Application Reset",
                footer=ui.div(
                    ui.input_action_button("btn_cancel_restart", "Cancel", class_="btn-secondary me-2"),
                    ui.input_action_button("btn_confirm_restart", "Reset", class_="btn-danger"),
                    class_="d-flex justify-content-end"
                ),
                easy_close=True
            )
        )

    @reactive.effect
    @reactive.event(input.btn_cancel_restart)
    def handle_cancel_restart():
        ui.modal_remove()

    @reactive.effect
    @reactive.event(input.btn_confirm_restart)
    async def handle_confirm_restart():
        ui.modal_remove()
        await session.send_custom_message("refresh_page", {})


#### App ####
app = App(
    ui=app_ui,
    server=server,
    static_assets=www_dir
)
